# Generated by Django 3.2.7 on 2021-09-29 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('top', '0003_submission_input'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='language',
            field=models.CharField(blank=True, choices=[('C++', 'C++'), ('Python', 'Python'), ('C', 'C')], max_length=100, null=True),
        ),
    ]
